server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          password: ''
          searchPaths: respo
          uri: https://github.com/meijindeng/sb-and-sc/
          username: ''